export const freelancerData = [
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    }
]

export const skillIconsImage = {
    "Python": "/assets/images/python.png",
    "ReactJS": "/assets/images/react-js.png"
}