export const skillIconsImage = {
    "Python": "/assets/images/python.png",
    "ReactJS": "/assets/images/react-js.png"
}

export const freelancerData = [
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore)",
        "currentCompany": "CashGrail",
        "college": "College of Engineering Anna University Guindy",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Neha Gupta",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 3,
        "expectedJoining": "Immediate",
        "location": "Delhi",
        "currentCompany": "TechMinds",
        "college": "Delhi University",
        "expectedSalary": "₹25L/yr current (₹30L/yr minimum expected)",
        "skills": ["Java", "Spring Boot", "MySQL", "AWS", "Docker"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Rahul Mehta",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 7,
        "expectedJoining": "15 days",
        "location": "Mumbai",
        "currentCompany": "InstaTech",
        "college": "IIT Bombay",
        "expectedSalary": "₹50L/yr current (₹60L/yr minimum expected)",
        "skills": ["Node.js", "Express", "MongoDB", "AWS", "GraphQL"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Sakshi Patel",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 2,
        "expectedJoining": "45 days",
        "location": "Pune",
        "currentCompany": "InfoEdge",
        "college": "Pune University",
        "expectedSalary": "₹15L/yr current (₹18L/yr minimum expected)",
        "skills": ["Angular", "TypeScript", "CSS", "HTML", "JavaScript"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Vikas Desai",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 6,
        "expectedJoining": "30 days",
        "location": "Hyderabad",
        "currentCompany": "Cyware",
        "college": "BITS Pilani",
        "expectedSalary": "₹40L/yr current (₹48L/yr minimum expected)",
        "skills": ["ReactJS", "Redux", "GraphQL", "TypeScript", "Jest"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Pooja Singh",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 4,
        "expectedJoining": "60 days",
        "location": "Chennai",
        "currentCompany": "TCS",
        "college": "Anna University",
        "expectedSalary": "₹22L/yr current (₹28L/yr minimum expected)",
        "skills": ["JavaScript", "Node.js", "Express", "MongoDB", "AWS"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Rohan Kapoor",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "15 days",
        "location": "Kolkata",
        "currentCompany": "WebWorks",
        "college": "Jadavpur University",
        "expectedSalary": "₹35L/yr current (₹40L/yr minimum expected)",
        "skills": ["Python", "Django", "Flask", "PostgreSQL", "Docker"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Sneha Nair",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 8,
        "expectedJoining": "Immediate",
        "location": "Kochi",
        "currentCompany": "MindTree",
        "college": "Cochin University",
        "expectedSalary": "₹45L/yr current (₹52L/yr minimum expected)",
        "skills": ["Java", "Spring", "Hibernate", "MySQL", "Kubernetes"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Akhil Verma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 3,
        "expectedJoining": "Immediate",
        "location": "Ahmedabad",
        "currentCompany": "Infosys",
        "college": "Nirma University",
        "expectedSalary": "₹28L/yr current (₹32L/yr minimum expected)",
        "skills": ["ReactJS", "Redux", "CSS", "JavaScript", "Node.js"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Divya Jain",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 6,
        "expectedJoining": "30 days",
        "location": "Gurgaon",
        "currentCompany": "Cognizant",
        "college": "Delhi University",
        "expectedSalary": "₹38L/yr current (₹45L/yr minimum expected)",
        "skills": ["Python", "Flask", "PostgreSQL", "Docker", "Kubernetes"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Ankit Saxena",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 7,
        "expectedJoining": "Immediate",
        "location": "Noida",
        "currentCompany": "HCL Technologies",
        "college": "Amity University",
        "expectedSalary": "₹50L/yr current (₹55L/yr minimum expected)",
        "skills": ["Java", "Spring Boot", "Microservices", "AWS", "Docker"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Ritika Malhotra",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 4,
        "expectedJoining": "45 days",
        "location": "Jaipur",
        "currentCompany": "Wipro",
        "college": "BITS Pilani",
        "expectedSalary": "₹26L/yr current (₹30L/yr minimum expected)",
        "skills": ["Angular", "TypeScript", "HTML", "CSS", "JavaScript"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Ajay Kumar",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 8,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore)",
        "currentCompany": "Capgemini",
        "college": "RV College of Engineering",
        "expectedSalary": "₹55L/yr current (₹60L/yr minimum expected)",
        "skills": ["JavaScript", "Node.js", "Express", "MongoDB", "ReactJS"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Preeti Raj",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "60 days",
        "location": "Lucknow",
        "currentCompany": "TCS",
        "college": "Lucknow University",
        "expectedSalary": "₹30L/yr current (₹35L/yr minimum expected)",
        "skills": ["Java", "Spring", "Hibernate", "Oracle", "Microservices"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Manish Kumar",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 9,
        "expectedJoining": "Immediate",
        "location": "Patna",
        "currentCompany": "IBM",
        "college": "NIT Patna",
        "expectedSalary": "₹60L/yr current (₹65L/yr minimum expected)",
        "skills": ["Python", "Django", "AWS", "PostgreSQL", "Docker"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Aarti Singh",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 3,
        "expectedJoining": "45 days",
        "location": "Nagpur",
        "currentCompany": "Infosys",
        "college": "Nagpur University",
        "expectedSalary": "₹24L/yr current (₹28L/yr minimum expected)",
        "skills": ["ReactJS", "Redux", "TypeScript", "JavaScript", "CSS"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Karthik Nair",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 6,
        "expectedJoining": "15 days",
        "location": "Thiruvananthapuram",
        "currentCompany": "Accenture",
        "college": "IIT Madras",
        "expectedSalary": "₹48L/yr current (₹55L/yr minimum expected)",
        "skills": ["Node.js", "Express", "MongoDB", "AWS", "GraphQL"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Shreya Bhatt",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 4,
        "expectedJoining": "60 days",
        "location": "Indore",
        "currentCompany": "Persistent Systems",
        "college": "IIT Indore",
        "expectedSalary": "₹32L/yr current (₹38L/yr minimum expected)",
        "skills": ["Angular", "TypeScript", "CSS", "HTML", "JavaScript"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Nitin Malhotra",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 7,
        "expectedJoining": "Immediate",
        "location": "Surat",
        "currentCompany": "Tata Consultancy Services",
        "college": "IIT Roorkee",
        "expectedSalary": "₹52L/yr current (₹60L/yr minimum expected)",
        "skills": ["Python", "Flask", "Django", "PostgreSQL", "Docker"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Megha Joshi",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 2,
        "expectedJoining": "45 days",
        "location": "Bhopal",
        "currentCompany": "Infosys",
        "college": "NIT Bhopal",
        "expectedSalary": "₹20L/yr current (₹25L/yr minimum expected)",
        "skills": ["Java", "Spring Boot", "Microservices", "MySQL", "Docker"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Vivek Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 8,
        "expectedJoining": "15 days",
        "location": "Raipur",
        "currentCompany": "Tech Mahindra",
        "college": "IIT Kharagpur",
        "expectedSalary": "₹58L/yr current (₹65L/yr minimum expected)",
        "skills": ["ReactJS", "Redux", "Node.js", "Express", "MongoDB"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Ruchi Verma",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Varanasi",
        "currentCompany": "Capgemini",
        "college": "IIT BHU",
        "expectedSalary": "₹35L/yr current (₹40L/yr minimum expected)",
        "skills": ["Python", "Django", "Flask", "PostgreSQL", "Docker"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Aditya Reddy",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 6,
        "expectedJoining": "Immediate",
        "location": "Vijayawada",
        "currentCompany": "Wipro",
        "college": "IIT Hyderabad",
        "expectedSalary": "₹42L/yr current (₹50L/yr minimum expected)",
        "skills": ["Java", "Spring", "Hibernate", "MySQL", "Kubernetes"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Sonal Gupta",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 4,
        "expectedJoining": "60 days",
        "location": "Guwahati",
        "currentCompany": "IBM",
        "college": "IIT Guwahati",
        "expectedSalary": "₹28L/yr current (₹32L/yr minimum expected)",
        "skills": ["ReactJS", "TypeScript", "JavaScript", "CSS", "HTML"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Rohit Sinha",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 7,
        "expectedJoining": "Immediate",
        "location": "Chandigarh",
        "currentCompany": "Infosys",
        "college": "PEC Chandigarh",
        "expectedSalary": "₹48L/yr current (₹55L/yr minimum expected)",
        "skills": ["Python", "Django", "Flask", "AWS", "Docker"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Pooja Choudhary",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "45 days",
        "location": "Jodhpur",
        "currentCompany": "Accenture",
        "college": "IIT Jodhpur",
        "expectedSalary": "₹34L/yr current (₹40L/yr minimum expected)",
        "skills": ["Angular", "TypeScript", "CSS", "JavaScript", "HTML"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Rajesh Nair",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 9,
        "expectedJoining": "30 days",
        "location": "Coimbatore",
        "currentCompany": "TCS",
        "college": "Amrita University",
        "expectedSalary": "₹65L/yr current (₹70L/yr minimum expected)",
        "skills": ["Java", "Spring Boot", "Microservices", "AWS", "Docker"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Nisha Agarwal",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 3,
        "expectedJoining": "Immediate",
        "location": "Kanpur",
        "currentCompany": "Infosys",
        "college": "IIT Kanpur",
        "expectedSalary": "₹30L/yr current (₹35L/yr minimum expected)",
        "skills": ["ReactJS", "Redux", "TypeScript", "JavaScript", "CSS"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Arjun Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 6,
        "expectedJoining": "15 days",
        "location": "Bengaluru (Bangalore)",
        "currentCompany": "Tech Mahindra",
        "college": "IIT Bombay",
        "expectedSalary": "₹42L/yr current (₹50L/yr minimum expected)",
        "skills": ["Node.js", "Express", "MongoDB", "AWS", "GraphQL"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Reena Reddy",
        "userStatus": "Open to Opportunities",
        "resumeLink": "#",
        "experience": 7,
        "expectedJoining": "Immediate",
        "location": "Mysore",
        "currentCompany": "Capgemini",
        "college": "IIT Madras",
        "expectedSalary": "₹48L/yr current (₹55L/yr minimum expected)",
        "skills": ["JavaScript", "Node.js", "Express", "MongoDB", "ReactJS"]
    }
];



export const freelancerData1 = [
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    },
    {
        "userImage": "https://via.placeholder.com/150",
        "userName": "Amit Sharma",
        "userStatus": "Actively Looking",
        "resumeLink": "#",
        "experience": 5,
        "expectedJoining": "30 days",
        "location": "Bengaluru (Bangalore) (Current), Can move to Ch Bengaluru (Bangalore) (Current), Can move to Ch",
        "currentCompany": "cashgrail (Current), Zupee, Omega Healthcare MA cashgrail (Current), Zupee, Omega Healthcare MA",
        "college": "College of Engineering Anna University Guindy, College of Engineering Anna University Guindy, C",
        "expectedSalary": "₹37L/yr current (₹44L/yr minimum expected)",
        "skills": ["Python", "ReactJS", "RestfulAPIs", "PostgreSQL", "Apache Kafka"]
    }
]
